<a href="https://colab.research.google.com/github/Prashanth-Telkar/ML-DL_Projects/blob/main/CIFAR_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# CNN FOR CIFAR-10 DATASET with Dropouts, BatchNormalization, l2_Normalization. 

In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.regularizers import l2
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
(X_train,y_train),(X_test,y_test)=cifar10.load_data()

In [4]:
X_train[0]

array([[[ 59,  62,  63],
        [ 43,  46,  45],
        [ 50,  48,  43],
        ...,
        [158, 132, 108],
        [152, 125, 102],
        [148, 124, 103]],

       [[ 16,  20,  20],
        [  0,   0,   0],
        [ 18,   8,   0],
        ...,
        [123,  88,  55],
        [119,  83,  50],
        [122,  87,  57]],

       [[ 25,  24,  21],
        [ 16,   7,   0],
        [ 49,  27,   8],
        ...,
        [118,  84,  50],
        [120,  84,  50],
        [109,  73,  42]],

       ...,

       [[208, 170,  96],
        [201, 153,  34],
        [198, 161,  26],
        ...,
        [160, 133,  70],
        [ 56,  31,   7],
        [ 53,  34,  20]],

       [[180, 139,  96],
        [173, 123,  42],
        [186, 144,  30],
        ...,
        [184, 148,  94],
        [ 97,  62,  34],
        [ 83,  53,  34]],

       [[177, 144, 116],
        [168, 129,  94],
        [179, 142,  87],
        ...,
        [216, 184, 140],
        [151, 118,  84],
        [123,  92,  72]]

In [5]:
X_train.shape

(50000, 32, 32, 3)

In [6]:
y_train.shape

(50000, 1)

In [7]:
y_train

array([[6],
       [9],
       [9],
       ...,
       [9],
       [1],
       [1]], dtype=uint8)

In [8]:
y_test.shape

(10000, 1)

In [9]:
y_train=tf.keras.utils.to_categorical(y_train,10)
y_train.shape

(50000, 10)

In [10]:
y_test=tf.keras.utils.to_categorical(y_test,10)
y_test.shape

(10000, 10)

In [11]:
X_train.dtype

dtype('uint8')

In [12]:
X_train=X_train.astype('float32')
X_test=X_test.astype('float32')

In [13]:
X_train.dtype

dtype('float32')

In [14]:
X_train/=255
X_test/=255
X_train[0]

array([[[0.23137255, 0.24313726, 0.24705882],
        [0.16862746, 0.18039216, 0.1764706 ],
        [0.19607843, 0.1882353 , 0.16862746],
        ...,
        [0.61960787, 0.5176471 , 0.42352942],
        [0.59607846, 0.49019608, 0.4       ],
        [0.5803922 , 0.4862745 , 0.40392157]],

       [[0.0627451 , 0.07843138, 0.07843138],
        [0.        , 0.        , 0.        ],
        [0.07058824, 0.03137255, 0.        ],
        ...,
        [0.48235294, 0.34509805, 0.21568628],
        [0.46666667, 0.3254902 , 0.19607843],
        [0.47843137, 0.34117648, 0.22352941]],

       [[0.09803922, 0.09411765, 0.08235294],
        [0.0627451 , 0.02745098, 0.        ],
        [0.19215687, 0.10588235, 0.03137255],
        ...,
        [0.4627451 , 0.32941177, 0.19607843],
        [0.47058824, 0.32941177, 0.19607843],
        [0.42745098, 0.28627452, 0.16470589]],

       ...,

       [[0.8156863 , 0.6666667 , 0.3764706 ],
        [0.7882353 , 0.6       , 0.13333334],
        [0.7764706 , 0

In [15]:
model=Sequential()

model.add(Conv2D(32,(3,3),padding='same',input_shape=X_train.shape[1:],activation='relu'))
model.add(BatchNormalization())
model.add(Conv2D(32,(3,3),activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))

model.add(Conv2D(64,(3,3),padding='same',input_shape=X_train.shape[1:],activation='relu'))
model.add(BatchNormalization())
model.add(Conv2D(64,(3,3),activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))

model.add(Conv2D(128,(3,3),padding='same',input_shape=X_train.shape[1:],activation='relu'))
model.add(BatchNormalization())
model.add(Conv2D(128,(3,3),activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(512,activation='relu',kernel_regularizer=l2(0.01))) 
model.add(Dropout(0.5))
model.add(Dense(10,activation='softmax'))

model.summary()



Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 32, 32, 32)        896       
                                                                 
 batch_normalization (BatchN  (None, 32, 32, 32)       128       
 ormalization)                                                   
                                                                 
 conv2d_1 (Conv2D)           (None, 30, 30, 32)        9248      
                                                                 
 batch_normalization_1 (Batc  (None, 30, 30, 32)       128       
 hNormalization)                                                 
                                                                 
 max_pooling2d (MaxPooling2D  (None, 15, 15, 32)       0         
 )                                                               
                                                        

In [16]:
model.compile(loss='categorical_crossentropy',optimizer='sgd',metrics=['accuracy'])

In [17]:
model.fit(X_train,y_train,batch_size=32,epochs=50,validation_data=(X_test,y_test),shuffle=True)

Epoch 1/50
1563/1563 [==============================] - 15s 8ms/step - loss: 5.5412 - accuracy: 0.3774 - val_loss: 4.3169 - val_accuracy: 0.4335
Epoch 2/50
1563/1563 [==============================] - 12s 8ms/step - loss: 3.3654 - accuracy: 0.5179 - val_loss: 2.7569 - val_accuracy: 0.5509
Epoch 3/50
1563/1563 [==============================] - 12s 7ms/step - loss: 2.2589 - accuracy: 0.5873 - val_loss: 1.8692 - val_accuracy: 0.6294
Epoch 4/50
1563/1563 [==============================] - 12s 8ms/step - loss: 1.6483 - accuracy: 0.6327 - val_loss: 1.4152 - val_accuracy: 0.6518
Epoch 5/50
1563/1563 [==============================] - 12s 7ms/step - loss: 1.3050 - accuracy: 0.6613 - val_loss: 1.1642 - val_accuracy: 0.6812
Epoch 6/50
1563/1563 [==============================] - 12s 7ms/step - loss: 1.0947 - accuracy: 0.6897 - val_loss: 1.0163 - val_accuracy: 0.7026
Epoch 7/50
1563/1563 [==============================] - 12s 7ms/step - loss: 0.9751 - accuracy: 0.7085 - val_loss: 0.8933 - val_ac

In [18]:
model.evaluate(X_test,y_test)

313/313 [==============================] - 1s 4ms/step - loss: 0.5831 - accuracy: 0.8407


[0.5831173062324524, 0.8406999707221985]